config/routes.rb
Rails.application.routes.draw do
  root to: "sandwiches#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :sandwiches, only: [:create, :new, :show, :destroy] do
    resources :shops, only: [:new, :create]
  end
  resources :ingredients, only: [:new, :create, :show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :shops
  has_many :sandwiches, :through => :shops, dependent: :destroy

  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/sandwich.rb
class Sandwich < ApplicationRecord
  has_one_attached :photo
  has_many :shops
  has_many :ingredients, :through => :shops, dependent: :destroy


  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :sandwich
  belongs_to :ingredient

  validates :ingredient_id, presence: true, uniqueness: { scope: :sandwich_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end
end

app/controllers/sandwiches_controller.rb
class SandwichesController < ApplicationController
  #before_action :set_sandwich

  def index
    @sandwiches = Sandwich.all
  end

  def show
    @sandwich = Sandwich.find(params[:id])
  end

  def new
    @sandwich = Sandwich.new
  end

  def create
    @sandwich = Sandwich.new(sandwich_params)
    if @sandwich.save
      redirect_to sandwich_path(@sandwich)
    else
      render :new, status: :unprocessable_entity
    end
  end
end

private

# def set_sandwich
#   @sandwich = Sandwich.find(params[:id])
# end

def sandwich_params
  params.require(:sandwich).permit(:description, :photo, :vegetarian, :cost, :name, :ingredient)
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_sandwich, only: %i[new create]

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
    @shop.sandwich = @sandwich
    if @shop.save
      redirect_to sandwich_path(@sandwich)
    else
      render :new, status: :unprocessable_entity
    end
  end

private

  def set_sandwich
    @sandwich = Sandwich.find(params[:sandwich_id])
  end

  def shop_params
    params.require(:shop).permit(:ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ingredients/index.html.erb
<div class="container">
  <div class="title-header">
    <h1>Fillings</h1>
  </div>
  <div class="container">
    <div class="cards">
      <% @ingredients.each do |ingredient| %>
        <%= link_to ingredient_path(ingredient) do %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= ingredient.image_url %>)">
            <%= ingredient.name %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/ingredients/show.html.erb
<div class="container">
  <div class="d-flex justify-content-center">
    <h1>Fillings</h1>
  </div>
  <div class="cards">
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%= @ingredient.shops.sandwich.name %></h5>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Purebread</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= render 'shared/header' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/sandwiches/index.html.erb
<div class="title-header">
  <div>
    <h1>Sandwiches</h1>
  </div>
  <div><%= link_to "Create a New Sandwich", new_sandwich_path, class: "btn btn-primary" %></div>
</div>
<div class="container" style="align-content-center">
  <div class="d-flex justify-content-center">
    <div class="row">
      <% @sandwiches.each do |sarny| %>
        <div class="card" style="width: 18rem;">
          <img src='<%= sarny.photo.attached? ? cl_image_path(sarny.photo.key) : "http://source.unsplash.com/featured/?#{sarny.name}sandwich&#{rand(1000)}" %>' class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title"><%= sarny.name %></h5>
            <p class="card-text"><%= sarny.description%></p>
            <%= link_to "Show Fillings", sandwich_path(sarny), class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/sandwiches/new.html.erb
<div class="container">
  <%= simple_form_for [@sandwich] do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.association :ingredients, :as => :radio_buttons, include_blank: false %>
    <%= f.input :description %>
    <%= f.submit 'Add Filling', class: 'btn btn-primary mt-2' %>
  <% end %>
</div>

app/views/sandwiches/show.html.erb
<div class="container">
  <div class="title-header">
    <h1>Fillings</h1>
    <div><%= link_to "Add a filling", new_sandwich_shop_path(@sandwich), class: "btn btn-blue" %></div>
  </div>
  <div class="cards">
    <% @sandwich.shops.each do |shop| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= shop.ingredient.image_url %>)">
        <%= shop.ingredient.name %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <h1 class="display-1">Pure Bread</h1>
  <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
    <li class="nav-item active">
      <%= link_to "Sandwiches", root_path, class: "nav-link" %>
    </li>
    <li class="nav-item active">
      <%= link_to "Fillings", ingredients_path, class:"nav-link" %>
    </li>
    <input type="search" class="form-control rounded" placeholder="Search" aria-label="Search" aria-describedby="search-addon"/>
    <span class="input-group-text border-0" id="search-addon">
      <i class="fas fa-search"></i>
    </span>
  </nav>
</nav>

app/views/shops/new.html.erb
<%= simple_form_for [@sandwich, @shop]  do |f| %>
  <%= f.association :ingredient %>
  <%= f.submit 'Add Filling', class: 'btn btn-primary mt-2' %>
<% end %>